{"uuid": "e46eac05-8da5-4dee-9f36-6e797c1f3269", "children": ["332eb486-6bb0-49e9-abdd-4b3944a365b3", "65194a21-4a10-4ef4-8658-2378b09d2361", "a1bbc5a6-2460-4d2c-94bd-08f209911c7d", "fb3e19bc-9b68-4cd9-bfab-d018cf8a9a35"], "befores": [{"name": "setup_teardown", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location\n\n", "trace": "  File \"G:\\automation\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"G:\\automation\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"G:\\automation\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"G:\\automation\\test_vcm_automation\\Test_base\\test_EnvironmentSetup.py\", line 13, in setup_teardown\n    self.driver = test_sellinium_functions.initialize_driver()\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"G:\\automation\\test_vcm_automation\\test_functions\\test_sellinium_functions.py\", line 10, in initialize_driver\n    return webdriver.Chrome()\n           ^^^^^^^^^^^^^^^^^^\n  File \"G:\\automation\\venv\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"G:\\automation\\venv\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 51, in __init__\n    self.service.path = DriverFinder.get_path(self.service, options)\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"G:\\automation\\venv\\Lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 41, in get_path\n    raise NoSuchDriverException(msg) from err\n"}, "start": 1692088914433, "stop": 1692088914904}], "start": 1692088914433, "stop": 1692088915208}